---
title: "Assignment 1 IDS 575"
author: "Talish Barmare"
date: "9/21/2019"


---
#Q5 & Q7 are in the pdf file

#Q8. This exercise relates to the “College” data set, which can be found in the file “College.csv”. It contains a number #of variables for 777 different universities and colleges in the US.

#a) Use the read.csv() function to read the data into R.
#Call the loaded data “college”. Make sure that you have the directory set to the correct location for the data.

getwd()
setwd("~/Desktop/IDS 575")

install.packages("ISLR")
library(ISLR)

college <- read.csv("College.csv")

#b) Look at the data using the fix() function. You should notice that the first column is just the name of each #university. We don’t really want R to treat this as data. However, it may be handy to have these names for later.


head(college)

rownames <- college[, 1]
college <- college[, -1]
head(college[, 1:5])

#c)
#i)Use the summary() function to produce a numerical summary of the variables in the data set.


summary(college)
#Private        Apps           Accept          Enroll       Top10perc       Top25perc      F.Undergrad     P.Undergrad     
# No :212   Min.   :   81   Min.   :   72   Min.   :  35   Min.   : 1.00   Min.   :  9.0   Min.   :  139   Min.   :    1.0  
# Yes:565   1st Qu.:  776   1st Qu.:  604   1st Qu.: 242   1st Qu.:15.00   1st Qu.: 41.0   1st Qu.:  992   1st Qu.:   95.0  
#           Median : 1558   Median : 1110   Median : 434   Median :23.00   Median : 54.0   Median : 1707   Median :  353.0  
#           Mean   : 3002   Mean   : 2019   Mean   : 780   Mean   :27.56   Mean   : 55.8   Mean   : 3700   Mean   :  855.3  
#           3rd Qu.: 3624   3rd Qu.: 2424   3rd Qu.: 902   3rd Qu.:35.00   3rd Qu.: 69.0   3rd Qu.: 4005   3rd Qu.:  967.0 # 
#           Max.   :48094   Max.   :26330   Max.   :6392   Max.   :96.00   Max.   :100.0   Max.   :31643   Max.   :21836.0  
#    Outstate       Room.Board       Books           Personal         PhD            Terminal       S.F.Ratio    
# Min.   : 2340   Min.   :1780   Min.   :  96.0   Min.   : 250   Min.   :  8.00   Min.   : 24.0   Min.   : 2.50  
# 1st Qu.: 7320   1st Qu.:3597   1st Qu.: 470.0   1st Qu.: 850   1st Qu.: 62.00   1st Qu.: 71.0   1st Qu.:11.50  
# Median : 9990   Median :4200   Median : 500.0   Median :1200   Median : 75.00   Median : 82.0   Median :13.60  
# Mean   :10441   Mean   :4358   Mean   : 549.4   Mean   :1341   Mean   : 72.66   Mean   : 79.7   Mean   :14.09  
# 3rd Qu.:12925   3rd Qu.:5050   3rd Qu.: 600.0   3rd Qu.:1700   3rd Qu.: 85.00   3rd Qu.: 92.0   3rd Qu.:16.50  
# Max.   :21700   Max.   :8124   Max.   :2340.0   Max.   :6800   Max.   :103.00   Max.   :100.0   Max.   :39.80  
#  perc.alumni        Expend        Grad.Rate     
# Min.   : 0.00   Min.   : 3186   Min.   : 10.00  
# 1st Qu.:13.00   1st Qu.: 6751   1st Qu.: 53.00  
# Median :21.00   Median : 8377   Median : 65.00  
# Mean   :22.74   Mean   : 9660   Mean   : 65.46  
# 3rd Qu.:31.00   3rd Qu.:10830   3rd Qu.: 78.00  
# Max.   :64.00   Max.   :56233   Max.   :118.00  


#ii) Use the pairs() function to produce a scatterplot matrix of
#the first ten columns or variables of the data. Recall that
#you can reference the first ten columns of a matrix A using A[,1:10].

pairs(college[, 1:10])

#iii) Use the plot() function to produce side-by-side boxplots of Outstate versus Private.

plot(college$Private, college$Outstate, xlab = "Private University", ylab ="Out of State tuition USD", main = "Outstate Tuition Vs Private Colleges")



#iv) Create a new qualitative variable, called Elite, by binning
#the Top10perc variable. We are going to divide universities
#of students coming from the top 10 % of their high school
#classes exceeds 50 %.


Elite <- rep("No", nrow(college))
Elite[college$Top10perc > 50] <- "Yes"
Elite <- as.factor(Elite)
college$Elite <- Elite
summary(college$Elite)

# No Yes 
#699  78 

plot(college$Elite, college$Outstate, xlab = "Elite University", ylab ="Out of State tuition in USD", main = "Outstate Tuition Plot")

#v) Use the hist() function to produce some histograms with
#differing numbers of bins for a few of the quantitative variables. You may find the command par(mfrow=c(2,2)) useful:
#it will divide the print window into four regions so that four
#plots can be made simultaneously. Modifying the arguments
#to this function will divide the screen in other ways.

par(mfrow = c(2,2))
hist(college$Books, col = 2, xlab = "Books", ylab = "Count", main = "Distribution of books cost in colleges")
hist(college$PhD, col = 3, xlab = "PhD", ylab = "Count",main = "Distribution of phd faculties accross colleges")
hist(college$Grad.Rate, col = 4, xlab = "Grad Rate", ylab = "Count",main = "Distribution of graduation rate in colleges")
hist(college$perc.alumni, col = 6, xlab = "% alumni", ylab = "Count",main = "Distribution of alumni who donated accross colleges")



#vi)Continue exploring the data, and provide a brief summary
#of what you discover.

#Some interesting observations: 

#What is the university with the most students in the top 10% of class
college[which.max(college$Top10perc),]  

rownames[355]
#Massachusetts Institute of Technology

#What university has the smallest & highest acceptance rates
college[ which.min( acceptance_rate ), ] 

acceptance_rate = college$Accept / college$Apps

college[ which.min( acceptance_rate ), ]

rownames[460]
#Princeton University

college[ which.max( acceptance_rate ), ] 

rownames[193]
#Emporia State University

#10)
library(MASS)

Boston
boston <- Boston

dim(boston)
summary(boston)

#    crim                zn             indus            chas              nox               rm             age        
# Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46   Min.   :0.00000   Min.   :0.3850   Min.   :3.561   Min.   :  2.90  
# 1st Qu.: 0.08204   1st Qu.:  0.00   1st Qu.: 5.19   1st Qu.:0.00000   1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02  
# Median : 0.25651   Median :  0.00   Median : 9.69   Median :0.00000   Median :0.5380   Median :6.208   Median : 77.50  
# Mean   : 3.61352   Mean   : 11.36   Mean   :11.14   Mean   :0.06917   Mean   :0.5547   Mean   :6.285   Mean   : 68.57  
# 3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000   3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08   # Max.   :88.97620   Max.   :100.00   Max.   :27.74   Max.   :1.00000   Max.   :0.8710   Max.   :8.780   Max.   :100.00  
#      dis              rad              tax           ptratio          black            lstat            medv      
# Min.   : 1.130   Min.   : 1.000   Min.   :187.0   Min.   :12.60   Min.   :  0.32   Min.   : 1.73   Min.   : 5.00  
# 1st Qu.: 2.100   1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40   1st Qu.:375.38   1st Qu.: 6.95   1st Qu.:17.02  
# Median : 3.207   Median : 5.000   Median :330.0   Median :19.05   Median :391.44   Median :11.36   Median :21.20  
# Mean   : 3.795   Mean   : 9.549   Mean   :408.2   Mean   :18.46   Mean   :356.67   Mean   :12.65   Mean   :22.53  
# 3rd Qu.: 5.188   3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20   3rd Qu.:396.23   3rd Qu.:16.95   3rd Qu.:25.00  
# Max.   :12.127   Max.   :24.000   Max.   :711.0   Max.   :22.00   Max.   :396.90   Max.   :37.97   Max.   :50.00  



?Boston

#b) Make some pairwise scatterplots of the predictors (columns) in
#this data set. Describe your findings.

par(mfrow = c(2, 2))
plot(Boston$nox, Boston$crim)
plot(Boston$rm, Boston$crim)
plot(Boston$age, Boston$crim)
plot(Boston$dis, Boston$crim)



#c)Are any of the predictors associated with per capita crime rate?
#If so, explain the relationship.
#There seems to be an association between the median value of owner-occupied homes and crime per capital. Low median value #of owner-occupied home indicates a higher crime per capita.

#There is also seem to be a correlation between distance to employment centers and crime. Areas close to employment #centers show high crime per capita.

dev.off()
hist(Boston$crim, breaks = 50)

#Most crime falls under 20% of Boston (80% of data falls in crim < 20)

pairs(Boston[Boston$crim < 20, ])

#There may be a relationship between crim and nox, rad, age, dis, lstat and medv.

plot(Boston$age, Boston$crim) # Older homes, more crime
plot(Boston$dis, Boston$crim) # Closer to work-area, more crime
plot(Boston$rad, Boston$crim) # Higher index of accessibility to radial highways, more crime
plot(Boston$medv, Boston$crim) # Higher crime in low median value houses 



#d) Do any of the suburbs of Boston appear to have particularly
#high crime rates? Tax rates? Pupil-teacher ratios? Comment on
#the range of each predictor.

par(mfrow=c(1,3))
hist(Boston$crim[Boston$crim>1], breaks=25)
# most cities have low crime rates, but there is a long tail: 18 suburbs appear
# to have a crime rate > 20, reaching to above 80
hist(Boston$tax, breaks=25)
# there is a large divide between suburbs with low tax rates and a peak at 660
hist(Boston$ptratio, breaks=25)
# a skew towards high ratios, but no particularly high ratios


dev.off()


#(e)How many of the suburbs in this data set bound the Charles river?
dim(subset(Boston, chas == 1))
# 35 suburbs

#f) What is the median pupil-teacher ratio among the towns in this data set ?

median(Boston$ptratio)

#19.05 is the ratio pupil-teacher

#g)Which suburb of Boston has lowest median value of owner-occupied homes ? What are the values of the other predictors #for that suburb, and how do those values compare to the overall ranges for those predictors ?

row.names(Boston[min(Boston$medv), ]) 
# lowest median value of owner-occupied homes 
# there are two suburbs with this value 399 and 406. 

#stats for 399 & 406

t(subset(Boston, medv == min(Boston$medv)))
#            399      406   comparison with overall ranges
# crim     38.3518  67.9208 above 3rd quartile
# zn        0.0000   0.0000 at min
# indus    18.1000  18.1000 at 3rd quartile
# chas      0.0000   0.0000 not bounded by river
# nox       0.6930   0.6930 above 3rd quartile
# rm        5.4530   5.6830 below 1st quartile
# age     100.0000 100.0000 at max
# dis       1.4896   1.4254 below 1st quartile
# rad      24.0000  24.0000 at max
# tax     666.0000 666.0000 at 3rd quartile
# ptratio  20.2000  20.2000 at 3rd quartile
# black   396.9000 384.9700 at max; above 1st quartile
# lstat    30.5900  22.9800 above 3rd quartile
# medv      5.0000   5.0000 at min

#Not the best place to live, but not too bad either


#h) In this data set, how many of the suburbs average more than
#seven rooms per dwelling? More than eight rooms per dwelling?
#Comment on the suburbs that average more than eight rooms
#per dwelling.

dim(subset(Boston, rm > 7))
# 64
dim(subset(Boston, rm > 8))
# 13
summary(subset(Boston, rm > 8))
summary(Boston)
# relatively lower crime (comparing range), lower lstat (comparing range)